include script; extend readme

diff --git a/workflows/team-syncer/action.yaml b/workflows/team-syncer/action.yaml
--- a/workflows/team-syncer/action.yaml
+++ b/workflows/team-syncer/action.yaml
@@ -14,9 +14,14 @@ runs:
   using: "composite"
   steps:
     - name: Set up environment
+      shell: bash
+      env:
+        YQ_VERSION: v4.44.2
       run: |
         sudo apt-get update
-        sudo apt-get install -y jq yq
+        sudo apt-get install -y jq curl wget tar
+        wget --no-verbose https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64.tar.gz -O - |\
+          tar xz && mv yq_linux_amd64 /usr/bin/yq
 
     - name: Sync teams to repository
       env:
@@ -25,6 +30,67 @@ runs:
         GITHUB_REPO: ${{ github.event.repository.name }}
         CONFIG_REPO: ${{ inputs.CONFIG_REPO }}
         CONFIG_FILE: ${{ inputs.CONFIG_FILE_PATH }}
+      shell: bash
       run: |
-        chmod +x sync_teams.sh
-        ./sync_teams.sh
+        set -ex
+        
+        GITHUB_TOKEN=${GITHUB_TOKEN}
+        
+        ORG_NAME=${GITHUB_ORG}
+        REPO_NAME=${GITHUB_REPO}
+        
+        CONFIG_REPO="${GITHUB_ORG}/common"
+        CONFIG_FILE="teams_config.yaml"
+        
+        SUPPORTED_PERMISSIONS=("pull" "push" "admin" "maintain" "triage")
+        
+        fetch_config() {
+          curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            -L "https://raw.githubusercontent.com/${CONFIG_REPO}/main/${CONFIG_FILE}" \
+            -o $CONFIG_FILE
+        }
+      
+        # Function to sync teams to a repository
+        sync_teams_to_repo() {
+          local team=$1
+          local permission=$2
+        
+          # Validate permission
+          local valid_permission=false
+          for p in "${SUPPORTED_PERMISSIONS[@]}"; do
+            if [[ "$p" == "$permission" ]]; then
+              valid_permission=true
+              break
+            fi
+          done
+        
+          if [[ "$valid_permission" == false ]]; then
+            echo "Invalid permission: $permission for team: $team. Skipping..."
+            return
+          fi
+        
+          curl -s -X PUT -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/orgs/$ORG_NAME/teams/$team/repos/$ORG_NAME/$REPO_NAME" \
+            -d "{\"permission\":\"$permission\"}"
+        }
+        
+        # Sync the teams to the repository.
+        fetch_config
+        teams=$(yq e '.teams' -o=json "$CONFIG_FILE")
+
+        # Check if teams is empty
+        if [ -z "$teams" ]; then
+          echo "No teams defined in $CONFIG_FILE"
+          exit 1
+        fi
+        
+        echo "$teams" | jq -c '.[]' | while read -r team; do
+          team_name=$(echo "$team" | jq -r '.name')
+          team_permission=$(echo "$team" | jq -r '.permission')
+        
+          echo "Syncing team: $team_name with permission: $team_permission"
+          continue
+          
+          sync_teams_to_repo $team_name $team_permission
+        done
